### PR TITLE
Full gene expression data set

### PR DESCRIPTION
**Pull request by sharlagelfand**
Use full gene expression data set in app, instead of a sample of 10,000. The data storage method is as described in #29 - parquet files partitioned by the first letter of the gene.

I expect a couple of NOTEs in R CMD check:
* Large data in inst/extdata/
* "no visible binding for global variable" notes due to the `.data` pronoun being removed, as we talked about - will keep an eye on the [issue I created in arrow](https://issues.apache.org/jira/browse/ARROW-10668) to see if any of the folks there have thoughts!

Note sure whether these NOTEs will cause the CI to fail - we can keep this PR as draft while I figure those two bits out if so.

### CODE REVIEW

**Comment by karawoo** [comment]
Thanks @sharlagelfand! I'm wondering if it would be better not to commit the parquet files to the repo, but rather maybe have  a script that generates them? We're not yet at GitHub's 100MB limit, but I think with these files we'd be halfway there. What do you think?

**Comment by sharlagelfand** [comment]
Ahh yes good call @karawoo! I've updated it to only commit an RDA file, and created a [new script](https://github.com/Sage-Bionetworks/magora/blob/parquet-first-letter/data-raw/gene_expressions_parquet.R) in `data-raw/` that reads that in and creates the parquet files (so we can run just that on the server).

**Comment by karawoo** [comment]
This works well for me, thanks @sharlagelfand! Can we just add a note to the README on how to generate the data if you're running the app locally, so that's documented?

**Comment by sharlagelfand** [comment]
thanks @karawoo, done! i've added info on how to run that script from the command line too (mostly for me inevitably having to look up how to run it on the server)

**Review by karawoo — APPROVED** [review]

**Pull request merged**
