### PR TITLE
Add ABCA7*V1599M data to pathology page

### LINKED ISSUE #111: pathology data- incorporate data from new model (ABCA7*V1599M)
There is another new model that we'd like to incorporate into the Pathology explorer. This model is ABCA7*V1599M.

The data sources and metadata identifiers can be found in the [ABCA7 tab in this spreadsheet](https://docs.google.com/spreadsheets/d/1B3ZMReC7nR2CGgpFNJuxJTj__lF2h6dt/edit#gid=1274984612).

The info to add this model to the model table is in red text on this sheet:
https://docs.google.com/spreadsheets/d/1KUctWyWRp0OXugmPeTUjzhRY0NvJf8QUKmrpyXmI54A/edit#gid=0

### PR DESCRIPTION
**Pull request by sharlagelfand**
Closes #111 - adding ABCA7*V1599M data to pathology page.

Only other difference is ensuring that the phenotypes are alphabetized on the pathology page as well!

PRing based off 103 since changes are branched from there - will update to PR into dev once that one is merged.

### CODE REVIEW

**Review by j-hendrickson-sage — APPROVED** [review]
Functionality looks good.

**Review by j-hendrickson-sage — APPROVED** [review]
Code appears good, although I would like to verify functionality with larger app.  Is there a branch I can pull?

**Comment by sharlagelfand** [comment]
The `issue-111` branch contains the functionality to be verified! Should work to just pull that.

**Review by j-hendrickson-sage — APPROVED** [review]
I see ABCA7*V1599M in pathology section

**Pull request merged**
